version: '3'

services:
  breakupbot_postgres:
    image: postgres
    container_name: 'breakupbot_postgres'
    restart: always
    ports:
      - 4001:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=breakupbot_db
    volumes:
      - '/var/lib/postgresql/data'
